server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/projet_pfa}
    username: ${SPRING_DATASOURCE_USERNAME:ecommerce}
    password: ${SPRING_DATASOURCE_PASSWORD:ecommerce}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      "[hibernate.format_sql]": true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
